[project]
name = "cloud-web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.0",
    "unicorn>=2.1.4",
    "uvicorn>=0.41.0",
    "ydb>=3.26.5",
]
